[package]
name = "smolix-build"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.4.1", features = ["auto-color"] }
ratatui = { version = "0.28.0", features = [] }
serde = { version = "1.0.205", features = ["derive"] }
serde_json = "1.0.122"
tui-tree-widget = "0.22.0"
